/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taskmanager_haroldmendoza_11541045;

import javax.swing.JOptionPane;

/**
 *
 * @author Harold Mendoza
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Task Manager | Harold Mendoza");
        this.setExtendedState(MAXIMIZED_BOTH);
        agregar();
        login(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_login = new javax.swing.JDialog();
        PanelLogin = new javax.swing.JPanel();
        jl_usuario = new javax.swing.JLabel();
        tf_login = new javax.swing.JTextField();
        jl_password = new javax.swing.JLabel();
        pf_passwordField = new javax.swing.JPasswordField();
        logo = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        bt_login = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        PanelLogin.setBackground(new java.awt.Color(44, 62, 80));
        PanelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelLogin.setInheritsPopupMenu(true);
        PanelLogin.setName("PanelLogin"); // NOI18N

        jl_usuario.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        jl_usuario.setText("usuario");

        jl_password.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jl_password.setForeground(new java.awt.Color(255, 255, 255));
        jl_password.setText("contraseña");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1493866002_Task_Manager_alt_2.png"))); // NOI18N

        logo2.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        logo2.setForeground(new java.awt.Color(0, 169, 236));
        logo2.setText("task manager");

        bt_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1493868701_Right_Arrow.png"))); // NOI18N
        bt_login.setBorderPainted(false);
        bt_login.setContentAreaFilled(false);
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLoginLayout = new javax.swing.GroupLayout(PanelLogin);
        PanelLogin.setLayout(PanelLoginLayout);
        PanelLoginLayout.setHorizontalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_login)
                    .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jl_usuario)
                        .addComponent(tf_login)
                        .addComponent(jl_password)
                        .addComponent(pf_passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                    .addComponent(logo2))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        PanelLoginLayout.setVerticalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jl_usuario)
                .addGap(18, 18, 18)
                .addComponent(tf_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jl_password)
                .addGap(18, 18, 18)
                .addComponent(pf_passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        // TODO add your handling code here:
         if (validarContacto(tf_login.getText(), pf_passwordField.getText())) {
            
            JOptionPane.showMessageDialog(this.jd_login, "Se Ingreso Exitosamente");
            this.jd_login.setVisible(false);
            this.setVisible(true);
            //JOptionPane.showMessageDialog(this, "Ha Ingresado al Sistema Exitosamente");
        } else {
            JOptionPane.showMessageDialog(this.jd_login, "Usuario Incorrecto");
        }
        tf_login.setText("");
        pf_passwordField.setText("");
    }//GEN-LAST:event_bt_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JButton bt_login;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDialog jd_login;
    private javax.swing.JLabel jl_password;
    private javax.swing.JLabel jl_usuario;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo2;
    private javax.swing.JPasswordField pf_passwordField;
    private javax.swing.JTextField tf_login;
    // End of variables declaration//GEN-END:variables


    administrarUsuarios usuarios = new administrarUsuarios("./Usuarios.txt"); 
    Usuario administrador = new Usuario("admin", "123");
    Usuario usuarioActual; 


    private boolean validarContacto(String nombre, String contraseña) {
        for (Usuario temp : usuarios.getListaUsuarios()) {
            if (nombre.equals(temp.getNombre()) && contraseña.equals(temp.getContraseña())) {
                usuarioActual=temp; 
                return true;
            }
        }
        return false;

    }
    
    private void login(boolean show){
        if(show){
            this.jd_login.setModal(true); // cuando las subventas se muestre, bloqueara el frame principal
            this.jd_login.pack(); //Redimensiona la ventana dependiendo de los controles que tenga en el frame
            this.jd_login.setLocationRelativeTo(this);
            this.jd_login.setVisible(true);
            this.setTitle("Login| Task Manager | Harold Mendoza");
        }
    
    }
    private void agregar() { // se agrega el administrador al arreglo de usuarios
        usuarios.cargarArchivo();  
    }



}
